/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceProductsRouteImport } from './routes/voice-products'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StoreQrRouteImport } from './routes/store-qr'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuickAddRouteImport } from './routes/quick-add'
import { Route as PurchasesRouteImport } from './routes/purchases'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as MenuQrRouteImport } from './routes/menu-qr'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as InvoiceDesignRouteImport } from './routes/invoice-design'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GoldRouteImport } from './routes/gold'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as MUserIdRouteImport } from './routes/m.$userId'

const VoiceProductsRoute = VoiceProductsRouteImport.update({
  id: '/voice-products',
  path: '/voice-products',
  getParentRoute: () => rootRouteImport,
} as any)
const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreQrRoute = StoreQrRouteImport.update({
  id: '/store-qr',
  path: '/store-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickAddRoute = QuickAddRouteImport.update({
  id: '/quick-add',
  path: '/quick-add',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasesRoute = PurchasesRouteImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuQrRoute = MenuQrRouteImport.update({
  id: '/menu-qr',
  path: '/menu-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceDesignRoute = InvoiceDesignRouteImport.update({
  id: '/invoice-design',
  path: '/invoice-design',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GoldRoute = GoldRouteImport.update({
  id: '/gold',
  path: '/gold',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MUserIdRoute = MUserIdRouteImport.update({
  id: '/m/$userId',
  path: '/m/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/backup': typeof BackupRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gold': typeof GoldRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/invoice-design': typeof InvoiceDesignRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/menu-qr': typeof MenuQrRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/quick-add': typeof QuickAddRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/renew': typeof RenewRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store-qr': typeof StoreQrRoute
  '/students': typeof StudentsRoute
  '/voice': typeof VoiceRoute
  '/voice-products': typeof VoiceProductsRoute
  '/m/$userId': typeof MUserIdRoute
  '/store/$storeId': typeof StoreStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/backup': typeof BackupRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gold': typeof GoldRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/invoice-design': typeof InvoiceDesignRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/menu-qr': typeof MenuQrRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/quick-add': typeof QuickAddRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/renew': typeof RenewRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store-qr': typeof StoreQrRoute
  '/students': typeof StudentsRoute
  '/voice': typeof VoiceRoute
  '/voice-products': typeof VoiceProductsRoute
  '/m/$userId': typeof MUserIdRoute
  '/store/$storeId': typeof StoreStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/backup': typeof BackupRoute
  '/customers': typeof CustomersRoute
  '/expenses': typeof ExpensesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gold': typeof GoldRoute
  '/history': typeof HistoryRoute
  '/inventory': typeof InventoryRoute
  '/invoice-design': typeof InvoiceDesignRoute
  '/invoices': typeof InvoicesRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/menu-qr': typeof MenuQrRoute
  '/production': typeof ProductionRoute
  '/products': typeof ProductsRoute
  '/purchases': typeof PurchasesRoute
  '/quick-add': typeof QuickAddRoute
  '/register': typeof RegisterRoute
  '/reminders': typeof RemindersRoute
  '/renew': typeof RenewRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store-qr': typeof StoreQrRoute
  '/students': typeof StudentsRoute
  '/voice': typeof VoiceRoute
  '/voice-products': typeof VoiceProductsRoute
  '/m/$userId': typeof MUserIdRoute
  '/store/$storeId': typeof StoreStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/backup'
    | '/customers'
    | '/expenses'
    | '/forgot-password'
    | '/gold'
    | '/history'
    | '/inventory'
    | '/invoice-design'
    | '/invoices'
    | '/login'
    | '/menu'
    | '/menu-qr'
    | '/production'
    | '/products'
    | '/purchases'
    | '/quick-add'
    | '/register'
    | '/reminders'
    | '/renew'
    | '/reports'
    | '/scan'
    | '/set-password'
    | '/settings'
    | '/sitemap.xml'
    | '/store-qr'
    | '/students'
    | '/voice'
    | '/voice-products'
    | '/m/$userId'
    | '/store/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/backup'
    | '/customers'
    | '/expenses'
    | '/forgot-password'
    | '/gold'
    | '/history'
    | '/inventory'
    | '/invoice-design'
    | '/invoices'
    | '/login'
    | '/menu'
    | '/menu-qr'
    | '/production'
    | '/products'
    | '/purchases'
    | '/quick-add'
    | '/register'
    | '/reminders'
    | '/renew'
    | '/reports'
    | '/scan'
    | '/set-password'
    | '/settings'
    | '/sitemap.xml'
    | '/store-qr'
    | '/students'
    | '/voice'
    | '/voice-products'
    | '/m/$userId'
    | '/store/$storeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/backup'
    | '/customers'
    | '/expenses'
    | '/forgot-password'
    | '/gold'
    | '/history'
    | '/inventory'
    | '/invoice-design'
    | '/invoices'
    | '/login'
    | '/menu'
    | '/menu-qr'
    | '/production'
    | '/products'
    | '/purchases'
    | '/quick-add'
    | '/register'
    | '/reminders'
    | '/renew'
    | '/reports'
    | '/scan'
    | '/set-password'
    | '/settings'
    | '/sitemap.xml'
    | '/store-qr'
    | '/students'
    | '/voice'
    | '/voice-products'
    | '/m/$userId'
    | '/store/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BackupRoute: typeof BackupRoute
  CustomersRoute: typeof CustomersRoute
  ExpensesRoute: typeof ExpensesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GoldRoute: typeof GoldRoute
  HistoryRoute: typeof HistoryRoute
  InventoryRoute: typeof InventoryRoute
  InvoiceDesignRoute: typeof InvoiceDesignRoute
  InvoicesRoute: typeof InvoicesRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MenuQrRoute: typeof MenuQrRoute
  ProductionRoute: typeof ProductionRoute
  ProductsRoute: typeof ProductsRoute
  PurchasesRoute: typeof PurchasesRoute
  QuickAddRoute: typeof QuickAddRoute
  RegisterRoute: typeof RegisterRoute
  RemindersRoute: typeof RemindersRoute
  RenewRoute: typeof RenewRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreQrRoute: typeof StoreQrRoute
  StudentsRoute: typeof StudentsRoute
  VoiceRoute: typeof VoiceRoute
  VoiceProductsRoute: typeof VoiceProductsRoute
  MUserIdRoute: typeof MUserIdRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice-products': {
      id: '/voice-products'
      path: '/voice-products'
      fullPath: '/voice-products'
      preLoaderRoute: typeof VoiceProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-qr': {
      id: '/store-qr'
      path: '/store-qr'
      fullPath: '/store-qr'
      preLoaderRoute: typeof StoreQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-add': {
      id: '/quick-add'
      path: '/quick-add'
      fullPath: '/quick-add'
      preLoaderRoute: typeof QuickAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchases': {
      id: '/purchases'
      path: '/purchases'
      fullPath: '/purchases'
      preLoaderRoute: typeof PurchasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu-qr': {
      id: '/menu-qr'
      path: '/menu-qr'
      fullPath: '/menu-qr'
      preLoaderRoute: typeof MenuQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice-design': {
      id: '/invoice-design'
      path: '/invoice-design'
      fullPath: '/invoice-design'
      preLoaderRoute: typeof InvoiceDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gold': {
      id: '/gold'
      path: '/gold'
      fullPath: '/gold'
      preLoaderRoute: typeof GoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$userId': {
      id: '/m/$userId'
      path: '/m/$userId'
      fullPath: '/m/$userId'
      preLoaderRoute: typeof MUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BackupRoute: BackupRoute,
  CustomersRoute: CustomersRoute,
  ExpensesRoute: ExpensesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GoldRoute: GoldRoute,
  HistoryRoute: HistoryRoute,
  InventoryRoute: InventoryRoute,
  InvoiceDesignRoute: InvoiceDesignRoute,
  InvoicesRoute: InvoicesRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MenuQrRoute: MenuQrRoute,
  ProductionRoute: ProductionRoute,
  ProductsRoute: ProductsRoute,
  PurchasesRoute: PurchasesRoute,
  QuickAddRoute: QuickAddRoute,
  RegisterRoute: RegisterRoute,
  RemindersRoute: RemindersRoute,
  RenewRoute: RenewRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreQrRoute: StoreQrRoute,
  StudentsRoute: StudentsRoute,
  VoiceRoute: VoiceRoute,
  VoiceProductsRoute: VoiceProductsRoute,
  MUserIdRoute: MUserIdRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
