/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoiceRouteImport } from './routes/voice'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SetPasswordRouteImport } from './routes/set-password'
import { Route as ScanRouteImport } from './routes/scan'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewRouteImport } from './routes/renew'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuickAddRouteImport } from './routes/quick-add'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StoreStoreIdRouteImport } from './routes/store.$storeId'
import { Route as MenuQrRouteImport } from './routes/menu.qr'
import { Route as MUserIdRouteImport } from './routes/m.$userId'

const VoiceRoute = VoiceRouteImport.update({
  id: '/voice',
  path: '/voice',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SetPasswordRoute = SetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ScanRoute = ScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewRoute = RenewRouteImport.update({
  id: '/renew',
  path: '/renew',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickAddRoute = QuickAddRouteImport.update({
  id: '/quick-add',
  path: '/quick-add',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreStoreIdRoute = StoreStoreIdRouteImport.update({
  id: '/store/$storeId',
  path: '/store/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuQrRoute = MenuQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => MenuRoute,
} as any)
const MUserIdRoute = MUserIdRouteImport.update({
  id: '/m/$userId',
  path: '/m/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/products': typeof ProductsRoute
  '/quick-add': typeof QuickAddRoute
  '/register': typeof RegisterRoute
  '/renew': typeof RenewRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/m/$userId': typeof MUserIdRoute
  '/menu/qr': typeof MenuQrRoute
  '/store/$storeId': typeof StoreStoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/products': typeof ProductsRoute
  '/quick-add': typeof QuickAddRoute
  '/register': typeof RegisterRoute
  '/renew': typeof RenewRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/m/$userId': typeof MUserIdRoute
  '/menu/qr': typeof MenuQrRoute
  '/store/$storeId': typeof StoreStoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/customers': typeof CustomersRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRouteWithChildren
  '/products': typeof ProductsRoute
  '/quick-add': typeof QuickAddRoute
  '/register': typeof RegisterRoute
  '/renew': typeof RenewRoute
  '/reports': typeof ReportsRoute
  '/scan': typeof ScanRoute
  '/set-password': typeof SetPasswordRoute
  '/settings': typeof SettingsRoute
  '/voice': typeof VoiceRoute
  '/m/$userId': typeof MUserIdRoute
  '/menu/qr': typeof MenuQrRoute
  '/store/$storeId': typeof StoreStoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/customers'
    | '/history'
    | '/login'
    | '/menu'
    | '/products'
    | '/quick-add'
    | '/register'
    | '/renew'
    | '/reports'
    | '/scan'
    | '/set-password'
    | '/settings'
    | '/voice'
    | '/m/$userId'
    | '/menu/qr'
    | '/store/$storeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/customers'
    | '/history'
    | '/login'
    | '/menu'
    | '/products'
    | '/quick-add'
    | '/register'
    | '/renew'
    | '/reports'
    | '/scan'
    | '/set-password'
    | '/settings'
    | '/voice'
    | '/m/$userId'
    | '/menu/qr'
    | '/store/$storeId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/customers'
    | '/history'
    | '/login'
    | '/menu'
    | '/products'
    | '/quick-add'
    | '/register'
    | '/renew'
    | '/reports'
    | '/scan'
    | '/set-password'
    | '/settings'
    | '/voice'
    | '/m/$userId'
    | '/menu/qr'
    | '/store/$storeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CustomersRoute: typeof CustomersRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRouteWithChildren
  ProductsRoute: typeof ProductsRoute
  QuickAddRoute: typeof QuickAddRoute
  RegisterRoute: typeof RegisterRoute
  RenewRoute: typeof RenewRoute
  ReportsRoute: typeof ReportsRoute
  ScanRoute: typeof ScanRoute
  SetPasswordRoute: typeof SetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  VoiceRoute: typeof VoiceRoute
  MUserIdRoute: typeof MUserIdRoute
  StoreStoreIdRoute: typeof StoreStoreIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voice': {
      id: '/voice'
      path: '/voice'
      fullPath: '/voice'
      preLoaderRoute: typeof VoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/set-password': {
      id: '/set-password'
      path: '/set-password'
      fullPath: '/set-password'
      preLoaderRoute: typeof SetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scan': {
      id: '/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof ScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renew': {
      id: '/renew'
      path: '/renew'
      fullPath: '/renew'
      preLoaderRoute: typeof RenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-add': {
      id: '/quick-add'
      path: '/quick-add'
      fullPath: '/quick-add'
      preLoaderRoute: typeof QuickAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store/$storeId': {
      id: '/store/$storeId'
      path: '/store/$storeId'
      fullPath: '/store/$storeId'
      preLoaderRoute: typeof StoreStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu/qr': {
      id: '/menu/qr'
      path: '/qr'
      fullPath: '/menu/qr'
      preLoaderRoute: typeof MenuQrRouteImport
      parentRoute: typeof MenuRoute
    }
    '/m/$userId': {
      id: '/m/$userId'
      path: '/m/$userId'
      fullPath: '/m/$userId'
      preLoaderRoute: typeof MUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MenuRouteChildren {
  MenuQrRoute: typeof MenuQrRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuQrRoute: MenuQrRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CustomersRoute: CustomersRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRouteWithChildren,
  ProductsRoute: ProductsRoute,
  QuickAddRoute: QuickAddRoute,
  RegisterRoute: RegisterRoute,
  RenewRoute: RenewRoute,
  ReportsRoute: ReportsRoute,
  ScanRoute: ScanRoute,
  SetPasswordRoute: SetPasswordRoute,
  SettingsRoute: SettingsRoute,
  VoiceRoute: VoiceRoute,
  MUserIdRoute: MUserIdRoute,
  StoreStoreIdRoute: StoreStoreIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
